# TCL File Generated by Component Editor 18.1
# Tue Dec 15 12:55:05 CET 2020
# DO NOT MODIFY


# 
# NMEA_RX "NMEA_RX" v1.0
# Sofiane AOUCI 2020.12.15.12:55:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module NMEA_RX
# 
set_module_property DESCRIPTION ""
set_module_property NAME NMEA_RX
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Sofiane AOUCI"
set_module_property DISPLAY_NAME NMEA_RX
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL NMEA_RX_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NMEA_RX_avalon.vhd VHDL PATH ../../functions/SOPC/NMEA_RX_avalon.vhd TOP_LEVEL_FILE
add_fileset_file UART_RX.vhd VHDL PATH ../../functions/FPGA/UART_RX.vhd
add_fileset_file counter.vhd VHDL PATH ../../functions/FPGA/counter.vhd
add_fileset_file divider.vhd VHDL PATH ../../functions/FPGA/divider.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point RX_IN
# 
add_interface RX_IN conduit end
set_interface_property RX_IN associatedClock clock
set_interface_property RX_IN associatedReset reset
set_interface_property RX_IN ENABLED true
set_interface_property RX_IN EXPORT_OF ""
set_interface_property RX_IN PORT_NAME_MAP ""
set_interface_property RX_IN CMSIS_SVD_VARIABLES ""
set_interface_property RX_IN SVD_ADDRESS_GROUP ""

add_interface_port RX_IN rx_in new_signal Input 1


# 
# connection point data_valid_out
# 
add_interface data_valid_out conduit end
set_interface_property data_valid_out associatedClock clock
set_interface_property data_valid_out associatedReset reset
set_interface_property data_valid_out ENABLED true
set_interface_property data_valid_out EXPORT_OF ""
set_interface_property data_valid_out PORT_NAME_MAP ""
set_interface_property data_valid_out CMSIS_SVD_VARIABLES ""
set_interface_property data_valid_out SVD_ADDRESS_GROUP ""

add_interface_port data_valid_out data_valid_out new_signal Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1

